### PR TITLE
Update and load avatar profile

### PR DESCRIPTION
**Pull request by marcoAntonioNina**
Feature https://github.com/ProcessMaker/bpm/issues/497

- Change profile avatar
- change rest api upload avatar, now accept image base64
- You must run `php artisan storage:link`

### CODE REVIEW

**Comment by velkymx** [comment]
It's not refreshing after uploading. you have to reload the page. Can you add the image URL return in the API return and update the different profile images?

**Comment by velkymx** [comment]
@marcoAntonioNina the default bubble is looking too big. Make sure it still matches the mockup.

screenshot 2018-08-15 10 56 12

**Comment by velkymx** [comment]
@marcoAntonioNina still some minor issues.

screenshot 2018-08-15 15 34 51

**Comment by velkymx** [comment]
Also, the font for the initials should not be bold.

**Comment by marcoAntonioNina** [comment]
I fixed comments

**Comment by velkymx** [comment]
@marcoAntonioNina merge dev. I'm getting conflicts.

**Pull request merged**
