### PR TITLE
Task Configuration Modal

### PR DESCRIPTION
**Pull request by danloa**
In the designer, when clicking on the gear that appears on the crown, a new popup modal appears. It allows to configure the task's name, form or script, and other attributes.

image
 
The items added/changed were:

-new modal-task-configuration.vue componente with the task properties form
-BPMNProcess.js, bpmn.js and Mutation.js were modifing based on a commit from @caleeli that allows the communication between the popups and the designer.
- ProcessMaker.xsd definitions was modified to define the new attributes of the task 
- Changes to  diagram events and svgcanvas.vue to update the diagram with the changes made in the model.

Ref: #495

### CODE REVIEW

**Comment by velkymx** [comment]
Jest Tests are failing.

**Comment by danloa** [comment]
The problem was generated in the commit 6f04ec1, the merge inserted lines that mixed two regions of the code. A commit to fix this was added

**Comment by velkymx** [comment]
Need the task type "Form" with the config to select a preconfigured form from the second drop down.

**Comment by danloa** [comment]
The PR was updated with:
- Renaming task type from  Manual to Form
- Reactivity between the updated model and the diagram rendering

**Pull request merged**
