### PR TITLE
Feature/254 Process Lanes

### PR DESCRIPTION
**Pull request by hjonathan**
Features:
- To create a lane, drag the lane in the pool
- To add shape in lane, drag shape in the Lane

Issues:
- Add shape to lane directly from toolbar

### CODE REVIEW

**Comment by velkymx** [comment]
@hjonathan Also, the lanes seem to work only intermittently. Please review.

**Comment by hjonathan** [comment]
The problem: the lanes seem to work only intermittently is fixed.
The lanes don't have crown

**Comment by velkymx** [comment]
After adding a few elements - the designer becomes unresponsive.

screenshot 2018-06-25 10 20 34

**Comment by hjonathan** [comment]
@velkymx I fixed a problem with the click in shapes, but the problem
"After adding a few elements - the designer becomes unresponsive"   I can't reproduce
Please. Do you can record the way for reproduce the bug?

**Comment by hjonathan** [comment]
@velkymx. With the last commit is no possible add flow to the lanes

**Pull request merged**
