### PR TITLE
Add a simple responsive email template

### LINKED ISSUE #1005: Email Template
Let's pick a default template to style our emails going out.

Ideas: https://mailchimp.com/features/email-templates/

Engineering Notes:
Also a good simple template: https://github.com/leemunroe/responsive-html-email-template
Probably need to inline styles: https://github.com/Automattic/juice

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes #1005 

A few updates to bpm-package-email-connector and vue-form-builder

Started with this template: https://github.com/leemunroe/responsive-html-email-template

Here's how it looks on mailtrap:

image

And gmail. Gmail does some weird stuff to our CSS that I'm not sure we can fix:

image

### CODE REVIEW

**Comment by velkymx** [comment]
@nolanpro 
[email_template.txt](https://github.com/ProcessMaker/bpm/files/2715461/email_template.txt)
Attached is an email template. Please let me know when it's integrated.

**Comment by nolanpro** [comment]
@velkymx Looking much better. Gmail doesn't support SVG though.

Gmail:

image

Mailtrap:

image

**Comment by velkymx** [comment]
@nolanpro please use the processmaker repo for the connector
https://github.com/ProcessMaker/pm4-connector-send-email

**Comment by nolanpro** [comment]
@velkymx looks like it already is https://github.com/ProcessMaker/bpm/blob/8380bbbbfde9019e9215163798e8f487f0200854/composer.json#L19

**Pull request merged**
