### PR TITLE
Unified the Models rules code

### PR DESCRIPTION
**Pull request by devmsh**

### CODE REVIEW

**Comment by devmsh** [comment]
Thanks @nolanpro

Once CircleCI is ready, I will submit many other enhancments 👍

**Comment by tdondich** [comment]
@nolanpro CircleCI won't run on this because it's an external fork.  I'm running the tests locally to verify.

**Comment by tdondich** [comment]
Sorry, cannot merge this one.  There are 3 test failures.  @devmsh , are you running phpunit?  Follow the instructions on how to setup the local dev environment and be sure to run vendor/bin/phpunit in the the virtualmachine once everything is installed.  Here's the output:

```Time: 1.46 minutes, Memory: 78.25MB

There were 3 failures:

1) Tests\Feature\Api\ScreenTest::testUpdateScreen
Expected status code 204 but received 422.
Failed asserting that false is true.

/home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:133
/home/vagrant/processmaker/tests/Feature/Api/ScreenTest.php:229

2) Tests\Feature\Api\ScreenTest::testUpdateSameTitleScreen
Expected status code 204 but received 422.
Failed asserting that false is true.

/home/vagrant/processmaker/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:133
/home/vagrant/processmaker/tests/Feature/Api/ScreenTest.php:267

3) Tests\Feature\AuthTest::testAuthManualLogin
Failed asserting that false is true.

/home/vagrant/processmaker/tests/Feature/AuthTest.php:46
```

**Comment by tdondich** [comment]
Also, since develop has changed fairly often on our repo, you might want to merge the latest develop on our side, to ensure your tests pass with most recent changes.

**Comment by devmsh** [comment]
@tdondich I rebase with the latest develop code, fix the `testUpdateScreen` and `testUpdateSameTitleScreen` but the `testAuthManualLogin` is already failed even in the develop so it's out of the scope of this PR.

**Comment by nolanpro** [comment]
@devmsh I'm currently working on `testAuthManualLogin`. Its failing locally for me too but not on CI for some reason. I'll let you know when I figure it out

**Comment by nolanpro** [comment]
@tdondich so this wouldn't work for us? https://circleci.com/docs/2.0/oss/#build-pull-requests-from-forked-repositories

**Comment by devmsh** [comment]
@nolanpro I just replace

```php
$user = factory(User::class)->create([
            'username' =>'newuser',
            'password' => Hash::make('password')
        ]);
```

with
```php
$user = factory(User::class)->create([
            'username' =>'newuser',
            'password' => 'password'
        ]);
```

and the test is pass

**Comment by nolanpro** [comment]
@devmsh Yeah that fixes it but there was a CircleCI config problem. Just waiting to get this PR merged: https://github.com/ProcessMaker/bpm/pull/931 Thanks!

**Pull request merged**
