### PR TITLE
Generate SDKs

### LINKED ISSUE #1473: Generate SDK
We need to be able to generate SDKs from Swagger that updates automatically when we build CircleCI using the swagger API. 

- [x] Generate for PHP
- [x] Generate for LUA
- [x] unit tests

To test: run `php artisan bpm:sdk php` and `php artisan bpm:sdk lua`. Verify clients are in storage/api/. Aactually running the sdk code will be tested as part of #1472

### PR DESCRIPTION
**Pull request by nolanpro**
Fixes #1473 

Circle CI will now build php and lua sdks and save them in storage/api

Testing the api generator. All commands should be run in the vagrant box:
The `php artisan bpm:sdk` takes 2 arguments. First the language and second is the output directory.
- Create a new output folder to hold the api. For example `mkdir /tmp/php-client-test`
- run `php artisan bpm:sdk php /tmp/php-client-test`
- Verify the sdk gets put in that folder and verify the settings in composer.json are correct
- For Lua, `mkdir lua-client-test` then `php artisan bpm:sdk lua ./lua-client-test`
- lua's version of composer.json is the `.rockspec` file it generates
- The output directory is what will be comitted to https://github.com/ProcessMaker/pm4-sdk-php and https://github.com/ProcessMaker/pm4-sdk-lua

Testing the docker implementation. All commands should be run in the vagrant box:
- Requires a branch from executor-php. So git clone that somewhere outside this repo
  `https://github.com/ProcessMaker/executor-php.git && cd executor-php && git checkout feature/1`
- composer install in the src folder `cd src && composer install`
- delete the old docker image if one exists `docker rmi processmaker/executor:php`
  - If it complains, stop any running containers then `docker container prune` and try the docker rmi command agian
- then back in the executor root, build the docker image `docker build -t processmaker/executor:php .`
- Now back in this repository, make sure you are running a NON-https bpm4 instance since the self-signed certificates have problems with the api. Check that APP_URL in your .env is not https
- Create a new php script with api calls
```
<?php
$emails = [];
foreach ($api->users()->getUsers()->getData() as $user) {
    $emails[] = $user->getEmail();
}
return ['emails' => $emails];
```
- Verify the script runs without errors and that you get the expected data. Add more users to see more emails in the example above.
- Reset db due to unrelated bug `php artisan migrate:fresh --seed --force && php artisan queue:restart`
- From the tests/Manual/PhpSDKScripts folder, import php_sdk_process.bpm4 and user_form_process.bpm4.
- Edit the scripts that got created from that import to set the run-as user to admin (we do not import users with the importer and all previous user associations are disassociated)
- Start a new 'PHP SDK Test' request
- (optional) Complete the new 'Pick color' task assigned to the logged in user
- Verify that after 5 minutes the 'PHP SDK Test' request completes automatically

### CODE REVIEW

**Comment by PMQABen** [comment]
**PHP:**
```
vagrant@bpm4:~/processmaker$ mkdir php-sdk-client-test
vagrant@bpm4:~/processmaker$ php artisan bpm:sdk ./php-sdk-client-test
ERROR: ./php-sdk-client-test language is not supported
vagrant@bpm4:~/processmaker$ php artisan bpm:sdk php ./php-sdk-client-test
Running: docker container ls -aq --filter='name=generator'
Got: ''
Running: docker pull openapitools/openapi-generator-online:v4.0.0-beta2
Got: 'v4.0.0-beta2: Pulling from openapitools/openapi-generator-online
169185f82c45: Pulling fs layer
3bdc61458cff: Pulling fs layer
6b1903cd06e3: Pulling fs layer
9cb4611b1af2: Pulling fs layer
a613deb61ef9: Pulling fs layer
9cb4611b1af2: Waiting
a613deb61ef9: Waiting
3bdc61458cff: Verifying Checksum
3bdc61458cff: Download complete
169185f82c45: Verifying Checksum
169185f82c45: Download complete
169185f82c45: Pull complete
9cb4611b1af2: Verifying Checksum
9cb4611b1af2: Download complete
3bdc61458cff: Pull complete
6b1903cd06e3: Verifying Checksum
6b1903cd06e3: Download complete
a613deb61ef9: Verifying Checksum
a613deb61ef9: Download complete
6b1903cd06e3: Pull complete
9cb4611b1af2: Pull complete
a613deb61ef9: Pull complete
Digest: sha256:8fde5278af00d4198d323ea3ebd447173fcdac0f5c1fe26a0d8cbc020b77ce29
Status: Downloaded newer image for openapitools/openapi-generator-online:v4.0.0-beta2'
Running: docker run -d --name generator -e GENERATOR_HOST=http://127.0.0.1:8080 openapitools/openapi-generator-online:v4.0.0-beta2
Got: '0f70a3f72176fef6be3603a84a7d73c938acaf5f1a15ed4b0f5f8bd4684c7a3c'
Running: docker exec generator apk add --update curl && rm -rf /var/cache/apk/*
Got: 'fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/4) Installing nghttp2-libs (1.32.0-r0)
(2/4) Installing libssh2 (1.8.0-r3)
(3/4) Installing libcurl (7.61.1-r2)
(4/4) Installing curl (7.61.1-r2)
Executing busybox-1.28.4-r3.trigger
OK: 83 MiB in 56 packages'
Running: docker start generator || echo "Container already running"
Got: 'generator'
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/clients/php
Not ready, trying again in 2 seconds. Cmd returned: 7 curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/clients/php
Not ready, trying again in 2 seconds. Cmd returned: 7 curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/clients/php
Not ready, trying again in 2 seconds. Cmd returned: 7 curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/clients/php
Not ready, trying again in 2 seconds. Cmd returned: 7 curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/clients/php
Not ready, trying again in 2 seconds. Cmd returned: 7 curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/clients/php
Not ready, trying again in 2 seconds. Cmd returned: 7 curl: (7) Failed to connect to 127.0.0.1 port 8080: Connection refused
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/clients/php
Got: 'MASSIVE_AMOUNTS_OF_JSON'
Running: docker exec generator curl -s -S -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d 'MASSIVE_AMOUNTS_OF_JSON"
Got: '{"code":"6af264d3-eec8-4d32-8d86-721ebce0081f","link":"http://127.0.0.1:8080/api/gen/download/6af264d3-eec8-4d32-8d86-721ebce0081f"}'
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/download/6af264d3-eec8-4d32-8d86-721ebce0081f > ./php-sdk-client-test/api.zip
Got: ''
Running: cp -rf /tmp/php-client/php-client/. ./php-sdk-client-test
Got: ''
DONE. Api is at ./php-sdk-client-test
vagrant@bpm4:~/processmaker$ ll php-sdk-client-test/
total 44
drwxr-xr-x 1 vagrant vagrant   416 Mar 12 20:37 ./
drwxr-xr-x 1 vagrant vagrant  1664 Mar 12 20:36 ../
-rw-r--r-- 1 vagrant vagrant  1025 Mar 12 20:37 composer.json
drwxr-xr-x 1 vagrant vagrant   128 Mar 12 20:37 docs/
-rw-r--r-- 1 vagrant vagrant  1650 Mar 12 20:37 git_push.sh
drwxr-xr-x 1 vagrant vagrant   256 Mar 12 20:37 lib/
drwxr-xr-x 1 vagrant vagrant    96 Mar 12 20:37 .openapi-generator/
-rw-r--r-- 1 vagrant vagrant  1040 Mar 12 20:37 .openapi-generator-ignore
-rw-r--r-- 1 vagrant vagrant   655 Mar 12 20:37 .php_cs
-rw-r--r-- 1 vagrant vagrant   691 Mar 12 20:37 phpunit.xml.dist
-rw-r--r-- 1 vagrant vagrant 17895 Mar 12 20:37 README.md
drwxr-xr-x 1 vagrant vagrant   128 Mar 12 20:37 test/
-rw-r--r-- 1 vagrant vagrant   146 Mar 12 20:37 .travis.yml
```
Contents of composer.json look good, has correct GitHub repo name.

```
vagrant@bpm4:~/processmaker$ rm -rf php-sdk-client-test/
vagrant@bpm4:~/processmaker$ php artisan l5:generate
Regenerating docs
vagrant@bpm4:~/processmaker$ mkdir php-sdk-client-test
vagrant@bpm4:~/processmaker$ php artisan bpm:sdk php ./php-sdk-client-test
Running: docker container ls -aq --filter='name=generator'
Got: '0f70a3f72176'
Running: docker start generator || echo 'Generator already started'
Got: 'generator'
Running: docker start generator || echo "Container already running"
Got: 'generator'
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/clients/php
Got: 'JSON!'
Running: docker exec generator curl -s -S -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d 'JSON!'
Got: '{"code":"9ac6b518-f1ce-4d76-bb2a-0c9b1b3dc9e0","link":"http://127.0.0.1:8080/api/gen/download/9ac6b518-f1ce-4d76-bb2a-0c9b1b3dc9e0"}'
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/download/9ac6b518-f1ce-4d76-bb2a-0c9b1b3dc9e0 > ./php-sdk-client-test/api.zip
Got: ''
Running: cp -rf /tmp/php-client/php-client/. ./php-sdk-client-test
Got: ''
DONE. Api is at ./php-sdk-client-test
vagrant@bpm4:~/processmaker$ 

```
Contents of composer.json look good, has correct GitHub repo name.

----

**Lua:**
```
vagrant@bpm4:~/processmaker$ mkdir lua-sdk-client-test
vagrant@bpm4:~/processmaker$ php artisan bpm:sdk lua ./lua-sdk-client-test
Running: docker container ls -aq --filter='name=generator'
Got: '0f70a3f72176'
Running: docker start generator || echo 'Generator already started'
Got: 'generator'
Running: docker start generator || echo "Container already running"
Got: 'generator'
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/clients/lua
Got: '{"packageName":{"opt":"packageName","description":"Lua package name (convention: single word).","type":"string","default":"openapiclient","enum":null},"packageVersion":{"opt":"packageVersion","description":"Lua package version.","type":"string","default":"1.0.0-1","enum":null},"hideGenerationTimestamp":{"opt":"hideGenerationTimestamp","description":"Hides the generation timestamp when files are generated.","type":"string","default":"true","enum":null}}'
Running: docker exec generator curl -s -S -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d 'MASSIVE_AMOUNTS_OF_JSON'
Got: '{"code":"23397a88-4f47-4d67-9256-9f09fc207b89","link":"http://127.0.0.1:8080/api/gen/download/23397a88-4f47-4d67-9256-9f09fc207b89"}'
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/download/23397a88-4f47-4d67-9256-9f09fc207b89 > ./lua-sdk-client-test/api.zip
Got: ''
Running: cp -rf /tmp/lua-client/lua-client/. ./lua-sdk-client-test
Got: ''
DONE. Api is at ./lua-sdk-client-test
vagrant@bpm4:~/processmaker$ ll lua-sdk-client-test/
total 20
drwxr-xr-x 1 vagrant vagrant  288 Mar 12 20:49 ./
drwxr-xr-x 1 vagrant vagrant 1664 Mar 12 20:49 ../
-rw-r--r-- 1 vagrant vagrant  323 Mar 12 20:49 .gitignore
-rw-r--r-- 1 vagrant vagrant 1650 Mar 12 20:49 git_push.sh
drwxr-xr-x 1 vagrant vagrant   96 Mar 12 20:49 .openapi-generator/
-rw-r--r-- 1 vagrant vagrant 1040 Mar 12 20:49 .openapi-generator-ignore
drwxr-xr-x 1 vagrant vagrant  128 Mar 12 20:49 pm4-sdk-lua/
-rw-r--r-- 1 vagrant vagrant 6994 Mar 12 20:49 pm4-sdk-lua-1.0.0-1.rockspec
drwxr-xr-x 1 vagrant vagrant 2464 Mar 12 20:49 spec/ 

```
Contents of pm4-sdk-lua-1.0.0-1.rockspec look good, points to the right GitHub repo.

```
vagrant@bpm4:~/processmaker$ rm -rf lua-sdk-client-test
vagrant@bpm4:~/processmaker$ php artisan l5:generate
Regenerating docs
vagrant@bpm4:~/processmaker$ mkdir lua-sdk-client-test
vagrant@bpm4:~/processmaker$ php artisan bpm:sdk lua ./lua-sdk-client-test
Running: docker container ls -aq --filter='name=generator'
Got: '0f70a3f72176'
Running: docker start generator || echo 'Generator already started'
Got: 'generator'
Running: docker start generator || echo "Container already running"
Got: 'generator'
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/clients/lua
Got: '{"packageName":{"opt":"packageName","description":"Lua package name (convention: single word).","type":"string","default":"openapiclient","enum":null},"packageVersion":{"opt":"packageVersion","description":"Lua package version.","type":"string","default":"1.0.0-1","enum":null},"hideGenerationTimestamp":{"opt":"hideGenerationTimestamp","description":"Hides the generation timestamp when files are generated.","type":"string","default":"true","enum":null}}'
Running: docker exec generator curl -s -S -H "Accept: application/json" -H "Content-Type: application/json" -X POST -d 'JSON!'
Got: '{"code":"ba6ead3d-672e-4073-8bd9-412e8f98b033","link":"http://127.0.0.1:8080/api/gen/download/ba6ead3d-672e-4073-8bd9-412e8f98b033"}'
Running: docker exec generator curl -s -S http://127.0.0.1:8080/api/gen/download/ba6ead3d-672e-4073-8bd9-412e8f98b033 > ./lua-sdk-client-test/api.zip
Got: ''
Running: cp -rf /tmp/lua-client/lua-client/. ./lua-sdk-client-test
Got: ''
DONE. Api is at ./lua-sdk-client-test
vagrant@bpm4:~/processmaker$ 
```
Contents of pm4-sdk-lua-1.0.0-1.rockspec look good, points to the right GitHub repo.

**Comment by ryancooley** [comment]
I've already talked to @nolanpro about these items and he was already aware of them but I want to note them here. These items may be best addressed if split into individual tickets:

- Should generate a README for the Lua SDK
- README for the PHP SDK should include instructions for the API wrapper rather than the individual APIs

**Comment by nolanpro** [comment]
> * Should generate a README for the Lua SDK

@ryancooley this is currently not supported in OpenAPI Generator. They commented it out: https://github.com/OpenAPITools/openapi-generator/blob/ce60dbbc585ca917abf0d0af8b9921215be8786d/modules/openapi-generator/src/main/java/org/openapitools/codegen/languages/LuaClientCodegen.java#L167

**Comment by ryancooley** [comment]
@velkymx I recommend approval of this PR.

**Pull request merged**
