### PR TITLE
remove unused packages

### LINKED ISSUE #1376: Remove Unused Packages
Verify that we need each package and remove unused ones.

### PR DESCRIPTION
**Pull request by milaendo**
closes #1376 

@PMQABen Please test this.

removed packages and tested from the list generated by depcheck.

### CODE REVIEW

**Comment by PMQABen** [comment]
Looks good! 👍

**Comment by velkymx** [comment]
@milaendo have we retested this? Is it ready?

**Comment by milaendo** [comment]
@marcoAntonioNina can you please take a look at this branch? the test the is failing was written by you but I am not understanding why it is failing. This ticket has only changed the package.json

**Comment by PMQABen** [comment]
Looks alright. Able to create users/screens/categories/processes/groups/etc, can archive/unarchive/run Processes.

**Comment by velkymx** [comment]
@PMQABen do the notifications work?

**Comment by PMQABen** [comment]
Yep, notifications appear, can be dismissed, works fine.

**Pull request closed without merging**
