### PR TITLE
Load shapes from XML #331

### PR DESCRIPTION
**Pull request by hjonathan**
Features:
- Load shapes from XML
- Drag BPMN file in canvas to load 
- Elements : 
   StartEvent, EndEvent, Task, CallActivity, inclusive Gateway. Exclusive Gateway, parallel Gateway, IntermediateCatchEvent, IntermediateThrowEvent, Participant

Problems:
- The implementation of flows will takes more time
- Others BPMN elements for example: IntermediateTimerEvent, SignalEvents still they are not implemented
 
capturadeepin20180628083809

The Bpmn file for the example:

[LoadBPMNElements.bpmn.zip](https://github.com/ProcessMaker/bpm/files/2145302/LoadBPMNElements.bpmn.zip)

### CODE REVIEW

**Comment by velkymx** [comment]
When I load a basic BPMN (attached) its rendering the lane off the screen. Merge develop and see if you can fix it.

Gmail_approval_template.bpmn
[Gmail_approval_template.bpmn.zip](https://github.com/ProcessMaker/bpm/files/2146393/Gmail_approval_template.bpmn.zip)

Screenshot
screenshot 2018-06-28 11 07 50

**Comment by hjonathan** [comment]
@velkymx  Fix the conflicts in pull request; 
The next file [Gmail_approval.bpmn.zip] is similar to Gmail_approval_template.bpmn.zip but with positive coordinates
[Gmail_approval.bpmn.zip](https://github.com/ProcessMaker/bpm/files/2147039/Gmail_approval.bpmn.zip)

**Comment by velkymx** [comment]
I think there is a use case for BPMN with negative coordinates. I'll open a ticket.

**Comment by velkymx** [comment]
close #331

**Pull request merged**
