### PR TITLE
User Profile Editor #292

### PR DESCRIPTION
**Pull request by milaendo**
screen shot 2018-06-21 at 1 03 56 pm
screen shot 2018-06-21 at 1 03 49 pm
screen shot 2018-06-21 at 1 03 42 pm

### CODE REVIEW

**Comment by velkymx** [comment]
When the modal pops up, just show the crop tool with the existing avatar preloaded

**Comment by velkymx** [comment]
What are the routes to test... I'm also getting an error: 

Trying to get property 'items' of non-object (View: /opt/processmaker/resources/views/layouts/navbar.blade.php) (View: /opt/processmaker/resources/views/layouts/navbar.blade.php) (View: /opt/processmaker/resources/views/layouts/navbar.blade.php) {"exception":"[object] (ErrorException(code: 0): Trying to get property 'items' of non-object (View: /opt/processmaker/resources/views/layouts/navbar.blade.php) (View: /opt/processmaker/resources/views/layouts/navbar.blade.php) (View: /opt/processmaker/resources/views/layouts/navbar.blade.php) at /opt/processmaker/storage/framework/views/0da5dcff3d66f837882455580adbbde0152267df.php:6, ErrorException(code: 0): Trying to get property 'items' of non-object (View: /opt/processmaker/resources/views/layouts/navbar.blade.php) (View: /opt/processmaker/resources/views/layouts/navbar.blade.php) at /opt/processmaker/storage/framework/views/0da5dcff3d66f837882455580adbbde0152267df.php:6, ErrorException(code: 0): Trying to get property 'items' of non-object (View: /opt/processmaker/resources/views/layouts/navbar.blade.php) at /opt/processmaker/storage/framework/views/0da5dcff3d66f837882455580adbbde0152267df.php:6, ErrorException(code: 0): Trying to get property 'items' of non-object at /opt/processmaker/storage/framework/views/0da5dcff3d66f837882455580adbbde0152267df.php:6)
[stacktrace]

**Comment by velkymx** [comment]
Still receiving an error: development.ERROR: Undefined variable: footer (View: /opt/processmaker/resources/views/auth/login.blade.php) {"exception":"[object] (ErrorException(code: 0): Undefined variable: footer (View: /opt/processmaker/resources/views/auth/login.blade.php) at /opt/processmaker/storage/framework/views/9b435f0ab4397c6affabb8c02f5af2c7577f66c8.php:71, ErrorException(code: 0): Undefined variable: footer at /opt/processmaker/storage/framework/views/9b435f0ab4397c6affabb8c02f5af2c7577f66c8.php:71)
[stacktrace]

**Comment by velkymx** [comment]
@milaendo This needs to use the profile API that Marco built to populate the form and to save on submit. Talk with him if there is confusion.

**Comment by velkymx** [comment]
@meadrat what does the All Processes button do? Is it a drop down?

**Comment by velkymx** [comment]
@milaendo is this correct?

screenshot 2018-07-02 16 28 44

**Comment by milaendo** [comment]
screen shot 2018-07-06 at 9 31 47 am

**Pull request merged**
